- name: Zookeeper | Install Java
  ansible.builtin.apt:
    name: "default-jre-headless"
    state: latest
    update_cache: true

- name: Zookeeper | Add Zookeeper user
  ansible.builtin.user:
    name: "zookeeper"
    shell: "/bin/false"
    system: false
    create_home: false

- name: Zookeeper | Make dir for zookeeper
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: zookeeper
    group: zookeeper
  loop:
  - "{{ zk_root_dir }}"
  - "{{ zk_data_dir }}"
  - /var/log/zookeeper

- name: Zookeeper | Download and unarchive zookeeper
  ansible.builtin.unarchive:
    #src: "https://dlcdn.apache.org/zookeeper/zookeeper-3.9.1/apache-zookeeper-3.9.1-bin.tar.gz"
    src: "https://archive.apache.org/dist/zookeeper/zookeeper-3.6.4/apache-zookeeper-3.6.4-bin.tar.gz"
    dest: "{{ zk_root_dir }}"
    remote_src: true
    extra_opts: 
    - "--strip-components=1"
    owner: zookeeper
    group: zookeeper

- name: Zookeeper | Copy systemd unit file
  ansible.builtin.template:
    src: "templates/zookeeper.service.j2"
    dest: /etc/systemd/system/zookeeper.service

- name: Zookeeper | Copy main config
  ansible.builtin.template:
    src: templates/zoo.cfg.j2
    dest: "{{ zk_root_dir }}/conf/zoo.cfg"
    owner: zookeeper
    group: zookeeper  
  notify: restart zookeeper

- name: Zookeeper | Configure zookeeper cluster
  ansible.builtin.template:
    src: templates/zoo.cfg.dynamic.j2
    dest: "{{ zk_root_dir }}/conf/zoo.cfg.dynamic"
    owner: zookeeper
    group: zookeeper
  notify: restart zookeeper

- name: Zookeeper | Configure id
  ansible.builtin.copy:
    dest: "{{ zk_data_dir }}/myid"
    content: "{{ my_id }}"
    owner: zookeeper
    group: zookeeper
  notify: restart zookeeper

- name: Zookeeper | Check if zookeeper is started
  ansible.builtin.systemd:
    name: zookeeper
    state: started
    daemon_reload: true
